packages:
  - "packages/*"
  - "examples/*"

catalogs:
  effect:
    effect: ^3.16.16
    "@effect/opentelemetry": ^0.54.1
    "@effect/platform": ^0.88.2
    "@effect/rpc": ^0.65.2
    "@effect/language-service": ^0.27.2